// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fancy_int.proto

#ifndef PROTOBUF_fancy_5fint_2eproto__INCLUDED
#define PROTOBUF_fancy_5fint_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace challenge {
class FancyInt;
class FancyIntDefaultTypeInternal;
extern FancyIntDefaultTypeInternal _FancyInt_default_instance_;
}  // namespace challenge

namespace challenge {

namespace protobuf_fancy_5fint_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_fancy_5fint_2eproto

// ===================================================================

class FancyInt : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:challenge.FancyInt) */ {
 public:
  FancyInt();
  virtual ~FancyInt();

  FancyInt(const FancyInt& from);

  inline FancyInt& operator=(const FancyInt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FancyInt& default_instance();

  static inline const FancyInt* internal_default_instance() {
    return reinterpret_cast<const FancyInt*>(
               &_FancyInt_default_instance_);
  }

  void Swap(FancyInt* other);

  // implements Message ----------------------------------------------

  inline FancyInt* New() const PROTOBUF_FINAL { return New(NULL); }

  FancyInt* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FancyInt& from);
  void MergeFrom(const FancyInt& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FancyInt* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 n = 1;
  bool has_n() const;
  void clear_n();
  static const int kNFieldNumber = 1;
  ::google::protobuf::uint32 n() const;
  void set_n(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:challenge.FancyInt)
 private:
  void set_has_n();
  void clear_has_n();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 n_;
  friend struct  protobuf_fancy_5fint_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FancyInt

// required uint32 n = 1;
inline bool FancyInt::has_n() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FancyInt::set_has_n() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FancyInt::clear_has_n() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FancyInt::clear_n() {
  n_ = 0u;
  clear_has_n();
}
inline ::google::protobuf::uint32 FancyInt::n() const {
  // @@protoc_insertion_point(field_get:challenge.FancyInt.n)
  return n_;
}
inline void FancyInt::set_n(::google::protobuf::uint32 value) {
  set_has_n();
  n_ = value;
  // @@protoc_insertion_point(field_set:challenge.FancyInt.n)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace challenge

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_fancy_5fint_2eproto__INCLUDED
