// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fancy_int.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "fancy_int.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace challenge {
class FancyIntDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<FancyInt> {
} _FancyInt_default_instance_;

namespace protobuf_fancy_5fint_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FancyInt, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FancyInt, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FancyInt, n_),
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 5, sizeof(FancyInt)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_FancyInt_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "fancy_int.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _FancyInt_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _FancyInt_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\017fancy_int.proto\022\tchallenge\"\025\n\010FancyInt"
      "\022\t\n\001n\030\001 \002(\r"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 51);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fancy_int.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_fancy_5fint_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FancyInt::kNFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FancyInt::FancyInt()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_fancy_5fint_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:challenge.FancyInt)
}
FancyInt::FancyInt(const FancyInt& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  n_ = from.n_;
  // @@protoc_insertion_point(copy_constructor:challenge.FancyInt)
}

void FancyInt::SharedCtor() {
  _cached_size_ = 0;
  n_ = 0u;
}

FancyInt::~FancyInt() {
  // @@protoc_insertion_point(destructor:challenge.FancyInt)
  SharedDtor();
}

void FancyInt::SharedDtor() {
}

void FancyInt::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FancyInt::descriptor() {
  protobuf_fancy_5fint_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_fancy_5fint_2eproto::file_level_metadata[0].descriptor;
}

const FancyInt& FancyInt::default_instance() {
  protobuf_fancy_5fint_2eproto::InitDefaults();
  return *internal_default_instance();
}

FancyInt* FancyInt::New(::google::protobuf::Arena* arena) const {
  FancyInt* n = new FancyInt;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FancyInt::Clear() {
// @@protoc_insertion_point(message_clear_start:challenge.FancyInt)
  n_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool FancyInt::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:challenge.FancyInt)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 n = 1;
      case 1: {
        if (tag == 8u) {
          set_has_n();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &n_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:challenge.FancyInt)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:challenge.FancyInt)
  return false;
#undef DO_
}

void FancyInt::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:challenge.FancyInt)
  // required uint32 n = 1;
  if (has_n()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->n(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:challenge.FancyInt)
}

::google::protobuf::uint8* FancyInt::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:challenge.FancyInt)
  // required uint32 n = 1;
  if (has_n()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->n(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:challenge.FancyInt)
  return target;
}

size_t FancyInt::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:challenge.FancyInt)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required uint32 n = 1;
  if (has_n()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->n());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FancyInt::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:challenge.FancyInt)
  GOOGLE_DCHECK_NE(&from, this);
  const FancyInt* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FancyInt>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:challenge.FancyInt)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:challenge.FancyInt)
    MergeFrom(*source);
  }
}

void FancyInt::MergeFrom(const FancyInt& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:challenge.FancyInt)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_n()) {
    set_n(from.n());
  }
}

void FancyInt::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:challenge.FancyInt)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FancyInt::CopyFrom(const FancyInt& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:challenge.FancyInt)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FancyInt::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void FancyInt::Swap(FancyInt* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FancyInt::InternalSwap(FancyInt* other) {
  std::swap(n_, other->n_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FancyInt::GetMetadata() const {
  protobuf_fancy_5fint_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_fancy_5fint_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FancyInt

// required uint32 n = 1;
bool FancyInt::has_n() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void FancyInt::set_has_n() {
  _has_bits_[0] |= 0x00000001u;
}
void FancyInt::clear_has_n() {
  _has_bits_[0] &= ~0x00000001u;
}
void FancyInt::clear_n() {
  n_ = 0u;
  clear_has_n();
}
::google::protobuf::uint32 FancyInt::n() const {
  // @@protoc_insertion_point(field_get:challenge.FancyInt.n)
  return n_;
}
void FancyInt::set_n(::google::protobuf::uint32 value) {
  set_has_n();
  n_ = value;
  // @@protoc_insertion_point(field_set:challenge.FancyInt.n)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace challenge

// @@protoc_insertion_point(global_scope)
